"""add conge_app tables

Revision ID: 1043ef9eeb3d
Revises: 13c5508e493d
Create Date: 2026-02-23 17:05:06.212084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1043ef9eeb3d'
down_revision: Union[str, Sequence[str], None] = '13c5508e493d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cg_jour_ferie',
    sa.Column('pays_code', sa.String(length=2), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('date_ferie', sa.Date(), nullable=False),
    sa.Column('type_date', sa.String(length=20), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('est_personnalise', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pays_code', 'nom', 'annee', name='uq_pays_nom_annee')
    )
    op.create_index('idx_ferie_date', 'cg_jour_ferie', ['date_ferie'], unique=False)
    op.create_index('idx_ferie_pays', 'cg_jour_ferie', ['pays_code'], unique=False)
    op.create_index(op.f('ix_cg_jour_ferie_annee'), 'cg_jour_ferie', ['annee'], unique=False)
    op.create_index(op.f('ix_cg_jour_ferie_date_ferie'), 'cg_jour_ferie', ['date_ferie'], unique=False)
    op.create_index(op.f('ix_cg_jour_ferie_id'), 'cg_jour_ferie', ['id'], unique=False)
    op.create_index(op.f('ix_cg_jour_ferie_pays_code'), 'cg_jour_ferie', ['pays_code'], unique=False)
    op.create_table('cg_type_conge',
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('nb_jours_max_par_an', sa.Float(), nullable=False),
    sa.Column('report_autorise', sa.Boolean(), nullable=False),
    sa.Column('necessite_validation', sa.Boolean(), nullable=False),
    sa.Column('niveaux_validation', sa.Integer(), nullable=False),
    sa.Column('couleur', sa.String(length=7), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cg_type_conge_code'), 'cg_type_conge', ['code'], unique=True)
    op.create_index(op.f('ix_cg_type_conge_id'), 'cg_type_conge', ['id'], unique=False)
    op.create_table('cg_demande_conge',
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('type_conge_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('est_demi_journee', sa.Boolean(), nullable=False),
    sa.Column('periode_demi_journee', sa.String(length=20), nullable=True),
    sa.Column('nb_jours_demandes', sa.Float(), nullable=False),
    sa.Column('nb_jours_ouvrables', sa.Float(), nullable=False),
    sa.Column('raison', sa.Text(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('niveau_validation_actuel', sa.Integer(), nullable=False),
    sa.Column('documents', sa.JSON(), nullable=False),
    sa.Column('date_soumission', sa.DateTime(), nullable=False),
    sa.Column('date_decision_finale', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employe_id'], ['rh_employe.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_conge_id'], ['cg_type_conge.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_demande_dates', 'cg_demande_conge', ['date_debut', 'date_fin'], unique=False)
    op.create_index('idx_demande_employe', 'cg_demande_conge', ['employe_id'], unique=False)
    op.create_index('idx_demande_statut', 'cg_demande_conge', ['statut'], unique=False)
    op.create_index('idx_demande_type', 'cg_demande_conge', ['type_conge_id'], unique=False)
    op.create_index(op.f('ix_cg_demande_conge_date_debut'), 'cg_demande_conge', ['date_debut'], unique=False)
    op.create_index(op.f('ix_cg_demande_conge_date_fin'), 'cg_demande_conge', ['date_fin'], unique=False)
    op.create_index(op.f('ix_cg_demande_conge_employe_id'), 'cg_demande_conge', ['employe_id'], unique=False)
    op.create_index(op.f('ix_cg_demande_conge_id'), 'cg_demande_conge', ['id'], unique=False)
    op.create_index(op.f('ix_cg_demande_conge_statut'), 'cg_demande_conge', ['statut'], unique=False)
    op.create_index(op.f('ix_cg_demande_conge_type_conge_id'), 'cg_demande_conge', ['type_conge_id'], unique=False)
    op.create_table('cg_solde_conge',
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('type_conge_id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('alloue', sa.Float(), nullable=False),
    sa.Column('utilise', sa.Float(), nullable=False),
    sa.Column('restant', sa.Float(), nullable=False),
    sa.Column('reporte', sa.Float(), nullable=False),
    sa.Column('date_expiration', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employe_id'], ['rh_employe.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_conge_id'], ['cg_type_conge.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employe_id', 'type_conge_id', 'annee', name='uq_employe_type_annee')
    )
    op.create_index('idx_solde_annee', 'cg_solde_conge', ['annee'], unique=False)
    op.create_index('idx_solde_employe', 'cg_solde_conge', ['employe_id'], unique=False)
    op.create_index(op.f('ix_cg_solde_conge_annee'), 'cg_solde_conge', ['annee'], unique=False)
    op.create_index(op.f('ix_cg_solde_conge_employe_id'), 'cg_solde_conge', ['employe_id'], unique=False)
    op.create_index(op.f('ix_cg_solde_conge_id'), 'cg_solde_conge', ['id'], unique=False)
    op.create_table('cg_historique_conge',
    sa.Column('demande_conge_id', sa.Integer(), nullable=False),
    sa.Column('niveau_validation', sa.Integer(), nullable=False),
    sa.Column('valideur_id', sa.Integer(), nullable=False),
    sa.Column('poste_valideur_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('date_action', sa.DateTime(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('delegue_a_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delegue_a_id'], ['user_management_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['demande_conge_id'], ['cg_demande_conge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poste_valideur_id'], ['rh_service_group.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['valideur_id'], ['user_management_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_historique_demande', 'cg_historique_conge', ['demande_conge_id'], unique=False)
    op.create_index('idx_historique_valideur', 'cg_historique_conge', ['valideur_id'], unique=False)
    op.create_index(op.f('ix_cg_historique_conge_demande_conge_id'), 'cg_historique_conge', ['demande_conge_id'], unique=False)
    op.create_index(op.f('ix_cg_historique_conge_id'), 'cg_historique_conge', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cg_historique_conge_id'), table_name='cg_historique_conge')
    op.drop_index(op.f('ix_cg_historique_conge_demande_conge_id'), table_name='cg_historique_conge')
    op.drop_index('idx_historique_valideur', table_name='cg_historique_conge')
    op.drop_index('idx_historique_demande', table_name='cg_historique_conge')
    op.drop_table('cg_historique_conge')
    op.drop_index(op.f('ix_cg_solde_conge_id'), table_name='cg_solde_conge')
    op.drop_index(op.f('ix_cg_solde_conge_employe_id'), table_name='cg_solde_conge')
    op.drop_index(op.f('ix_cg_solde_conge_annee'), table_name='cg_solde_conge')
    op.drop_index('idx_solde_employe', table_name='cg_solde_conge')
    op.drop_index('idx_solde_annee', table_name='cg_solde_conge')
    op.drop_table('cg_solde_conge')
    op.drop_index(op.f('ix_cg_demande_conge_type_conge_id'), table_name='cg_demande_conge')
    op.drop_index(op.f('ix_cg_demande_conge_statut'), table_name='cg_demande_conge')
    op.drop_index(op.f('ix_cg_demande_conge_id'), table_name='cg_demande_conge')
    op.drop_index(op.f('ix_cg_demande_conge_employe_id'), table_name='cg_demande_conge')
    op.drop_index(op.f('ix_cg_demande_conge_date_fin'), table_name='cg_demande_conge')
    op.drop_index(op.f('ix_cg_demande_conge_date_debut'), table_name='cg_demande_conge')
    op.drop_index('idx_demande_type', table_name='cg_demande_conge')
    op.drop_index('idx_demande_statut', table_name='cg_demande_conge')
    op.drop_index('idx_demande_employe', table_name='cg_demande_conge')
    op.drop_index('idx_demande_dates', table_name='cg_demande_conge')
    op.drop_table('cg_demande_conge')
    op.drop_index(op.f('ix_cg_type_conge_id'), table_name='cg_type_conge')
    op.drop_index(op.f('ix_cg_type_conge_code'), table_name='cg_type_conge')
    op.drop_table('cg_type_conge')
    op.drop_index(op.f('ix_cg_jour_ferie_pays_code'), table_name='cg_jour_ferie')
    op.drop_index(op.f('ix_cg_jour_ferie_id'), table_name='cg_jour_ferie')
    op.drop_index(op.f('ix_cg_jour_ferie_date_ferie'), table_name='cg_jour_ferie')
    op.drop_index(op.f('ix_cg_jour_ferie_annee'), table_name='cg_jour_ferie')
    op.drop_index('idx_ferie_pays', table_name='cg_jour_ferie')
    op.drop_index('idx_ferie_date', table_name='cg_jour_ferie')
    op.drop_table('cg_jour_ferie')
    # ### end Alembic commands ###
