"""Add password_reset_otp table

Revision ID: 13c5508e493d
Revises: f3f50a85e487
Create Date: 2026-02-19 23:43:41.618332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c5508e493d'
down_revision: Union[str, Sequence[str], None] = 'f3f50a85e487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('reset_token', sa.String(length=100), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_management_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_otp_email'), 'password_reset_otp', ['email'], unique=False)
    op.create_index(op.f('ix_password_reset_otp_id'), 'password_reset_otp', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_otp_reset_token'), 'password_reset_otp', ['reset_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_otp_reset_token'), table_name='password_reset_otp')
    op.drop_index(op.f('ix_password_reset_otp_id'), table_name='password_reset_otp')
    op.drop_index(op.f('ix_password_reset_otp_email'), table_name='password_reset_otp')
    op.drop_table('password_reset_otp')
    # ### end Alembic commands ###
