"""create_audit_log_table

Revision ID: 893871e59f44
Revises: 
Create Date: 2026-02-17 02:49:32.584571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '893871e59f44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rh_service',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rh_service_code'), 'rh_service', ['code'], unique=True)
    op.create_index(op.f('ix_rh_service_id'), 'rh_service', ['id'], unique=False)
    op.create_table('user_management_group',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_management_group_code'), 'user_management_group', ['code'], unique=True)
    op.create_index(op.f('ix_user_management_group_id'), 'user_management_group', ['id'], unique=False)
    op.create_table('user_management_permission',
    sa.Column('codename', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.Integer(), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("action IN ('CREATE', 'READ', 'UPDATE', 'DELETE')", name='ck_permission_action'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource', 'action', name='uq_permission_resource_action')
    )
    op.create_index(op.f('ix_user_management_permission_codename'), 'user_management_permission', ['codename'], unique=True)
    op.create_index(op.f('ix_user_management_permission_id'), 'user_management_permission', ['id'], unique=False)
    op.create_table('rh_service_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['user_management_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['rh_service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'group_id', name='uq_service_group')
    )
    op.create_index(op.f('ix_rh_service_group_id'), 'rh_service_group', ['id'], unique=False)
    op.create_table('rh_employe',
    sa.Column('prenom', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('postnom', sa.String(length=255), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=False),
    sa.Column('sexe', sa.String(length=1), nullable=False),
    sa.Column('statut_matrimonial', sa.String(length=1), nullable=False),
    sa.Column('nationalite', sa.String(length=100), nullable=False),
    sa.Column('banque', sa.String(length=255), nullable=False),
    sa.Column('numero_compte', sa.String(length=255), nullable=False),
    sa.Column('niveau_etude', sa.String(length=255), nullable=False),
    sa.Column('numero_inss', sa.String(length=255), nullable=False),
    sa.Column('email_personnel', sa.String(length=255), nullable=False),
    sa.Column('email_professionnel', sa.String(length=255), nullable=True),
    sa.Column('telephone_personnel', sa.String(length=17), nullable=False),
    sa.Column('telephone_professionnel', sa.String(length=17), nullable=True),
    sa.Column('adresse_ligne1', sa.String(length=200), nullable=False),
    sa.Column('adresse_ligne2', sa.String(length=200), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('code_postal', sa.String(length=20), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('matricule', sa.String(length=100), nullable=True),
    sa.Column('poste_id', sa.Integer(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('date_embauche', sa.Date(), nullable=False),
    sa.Column('statut_emploi', sa.String(length=20), nullable=False),
    sa.Column('nombre_enfants', sa.Integer(), nullable=False),
    sa.Column('nom_conjoint', sa.String(length=100), nullable=True),
    sa.Column('biographie', sa.Text(), nullable=True),
    sa.Column('nom_contact_urgence', sa.String(length=100), nullable=False),
    sa.Column('lien_contact_urgence', sa.String(length=50), nullable=False),
    sa.Column('telephone_contact_urgence', sa.String(length=17), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("sexe IN ('M', 'F', 'O')", name='ck_employe_sexe'),
    sa.CheckConstraint("statut_emploi IN ('ACTIVE', 'INACTIVE', 'TERMINATED', 'SUSPENDED')", name='ck_employe_statut_emploi'),
    sa.CheckConstraint("statut_matrimonial IN ('S', 'M', 'D', 'W')", name='ck_employe_statut_matrimonial'),
    sa.CheckConstraint('date_embauche <= CURRENT_DATE', name='ck_employe_date_embauche_past'),
    sa.CheckConstraint('nombre_enfants >= 0', name='ck_employe_nombre_enfants_positive'),
    sa.ForeignKeyConstraint(['poste_id'], ['rh_service_group.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responsable_id'], ['rh_employe.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_professionnel')
    )
    op.create_index(op.f('ix_rh_employe_id'), 'rh_employe', ['id'], unique=False)
    op.create_table('rh_contrat',
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('type_contrat', sa.String(length=50), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('salaire_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('indemnite_logement', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('indemnite_transport', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('indemnite_fonction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('devise', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("type_contrat IN ('CDI', 'CDD', 'STAGE', 'CONSULTANT')", name='ck_contrat_type_contrat'),
    sa.CheckConstraint('date_fin IS NULL OR date_fin > date_debut', name='ck_contrat_date_fin_after_debut'),
    sa.CheckConstraint('indemnite_fonction >= 0', name='ck_contrat_indemnite_fonction_positive'),
    sa.CheckConstraint('indemnite_logement >= 0', name='ck_contrat_indemnite_logement_positive'),
    sa.CheckConstraint('indemnite_transport >= 0', name='ck_contrat_indemnite_transport_positive'),
    sa.CheckConstraint('salaire_base > 0', name='ck_contrat_salaire_base_positive'),
    sa.ForeignKeyConstraint(['employe_id'], ['rh_employe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rh_contrat_id'), 'rh_contrat', ['id'], unique=False)
    op.create_table('rh_document',
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('type_document', sa.String(length=50), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fichier', sa.String(length=500), nullable=False),
    sa.Column('date_upload', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employe_id'], ['rh_employe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rh_document_id'), 'rh_document', ['id'], unique=False)
    op.create_table('user_management_user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('prenom', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employe_id'], ['rh_employe.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_management_user_email'), 'user_management_user', ['email'], unique=True)
    op.create_index(op.f('ix_user_management_user_id'), 'user_management_user', ['id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_key', sa.String(length=40), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.CheckConstraint("action IN ('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'LOGIN_FAILED', 'VIEW', 'VIEW_FAILED', 'EXPORT', 'BULK_OPERATION', 'CREATE_FAILED', 'UPDATE_FAILED', 'DELETE_FAILED')", name='ck_audit_action'),
    sa.ForeignKeyConstraint(['user_id'], ['user_management_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action_timestamp', 'audit_log', ['action', 'timestamp'], unique=False)
    op.create_index('idx_audit_ip_timestamp', 'audit_log', ['ip_address', 'timestamp'], unique=False)
    op.create_index('idx_audit_resource_timestamp', 'audit_log', ['resource_type', 'timestamp'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_index('idx_audit_user_timestamp', 'audit_log', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_table('user_management_grouppermission',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_management_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['user_management_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['user_management_permission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'permission_id', name='uq_group_permission')
    )
    op.create_index(op.f('ix_user_management_grouppermission_id'), 'user_management_grouppermission', ['id'], unique=False)
    op.create_table('user_management_usergroup',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['user_management_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['user_management_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_management_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_management_usergroup_id'), 'user_management_usergroup', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_management_usergroup_id'), table_name='user_management_usergroup')
    op.drop_table('user_management_usergroup')
    op.drop_index(op.f('ix_user_management_grouppermission_id'), table_name='user_management_grouppermission')
    op.drop_table('user_management_grouppermission')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index('idx_audit_user_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_resource_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_ip_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_action_timestamp', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_user_management_user_id'), table_name='user_management_user')
    op.drop_index(op.f('ix_user_management_user_email'), table_name='user_management_user')
    op.drop_table('user_management_user')
    op.drop_index(op.f('ix_rh_document_id'), table_name='rh_document')
    op.drop_table('rh_document')
    op.drop_index(op.f('ix_rh_contrat_id'), table_name='rh_contrat')
    op.drop_table('rh_contrat')
    op.drop_index(op.f('ix_rh_employe_id'), table_name='rh_employe')
    op.drop_table('rh_employe')
    op.drop_index(op.f('ix_rh_service_group_id'), table_name='rh_service_group')
    op.drop_table('rh_service_group')
    op.drop_index(op.f('ix_user_management_permission_id'), table_name='user_management_permission')
    op.drop_index(op.f('ix_user_management_permission_codename'), table_name='user_management_permission')
    op.drop_table('user_management_permission')
    op.drop_index(op.f('ix_user_management_group_id'), table_name='user_management_group')
    op.drop_index(op.f('ix_user_management_group_code'), table_name='user_management_group')
    op.drop_table('user_management_group')
    op.drop_index(op.f('ix_rh_service_id'), table_name='rh_service')
    op.drop_index(op.f('ix_rh_service_code'), table_name='rh_service')
    op.drop_table('rh_service')
    # ### end Alembic commands ###
