"""user_employe_cascade_delete

Revision ID: d7a92dd58145
Revises: 1043ef9eeb3d
Create Date: 2026-03-17 14:48:26.241186

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd7a92dd58145'
down_revision: Union[str, Sequence[str], None] = '1043ef9eeb3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_management_user_employe_id_fkey'), 'user_management_user', type_='foreignkey')
    op.create_foreign_key(None, 'user_management_user', 'rh_employe', ['employe_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_management_user', type_='foreignkey')
    op.create_foreign_key(op.f('user_management_user_employe_id_fkey'), 'user_management_user', 'rh_employe', ['employe_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
