"""add paie_app tables

Revision ID: f3f50a85e487
Revises: d58e0c172f99
Create Date: 2026-02-18 17:15:06.159643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f50a85e487'
down_revision: Union[str, Sequence[str], None] = 'd58e0c172f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paie_periode',
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('traite_par_id', sa.Integer(), nullable=True),
    sa.Column('date_traitement', sa.DateTime(), nullable=True),
    sa.Column('approuve_par_id', sa.Integer(), nullable=True),
    sa.Column('date_approbation', sa.DateTime(), nullable=True),
    sa.Column('nombre_employes', sa.Integer(), nullable=False),
    sa.Column('masse_salariale_brute', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_cotisations_patronales', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_cotisations_salariales', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_net_a_payer', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approuve_par_id'], ['user_management_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['traite_par_id'], ['user_management_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annee', 'mois', name='uq_annee_mois')
    )
    op.create_index(op.f('ix_paie_periode_id'), 'paie_periode', ['id'], unique=False)
    op.create_table('paie_retenu_salaire',
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('type_retenue', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('montant_mensuel', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('montant_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('montant_deja_deduit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('est_active', sa.Boolean(), nullable=False),
    sa.Column('est_recurrente', sa.Boolean(), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.Column('banque_beneficiaire', sa.String(length=255), nullable=True),
    sa.Column('compte_beneficiaire', sa.String(length=255), nullable=True),
    sa.Column('modification_history', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cree_par_id'], ['user_management_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employe_id'], ['rh_employe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paie_retenu_salaire_id'), 'paie_retenu_salaire', ['id'], unique=False)
    op.create_table('paie_alert',
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=True),
    sa.Column('periode_paie_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_by_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['user_management_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_management_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employe_id'], ['rh_employe.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['periode_paie_id'], ['paie_periode.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['user_management_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paie_alert_id'), 'paie_alert', ['id'], unique=False)
    op.create_table('paie_entree',
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('periode_paie_id', sa.Integer(), nullable=False),
    sa.Column('contrat_reference', sa.JSON(), nullable=False),
    sa.Column('salaire_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('indemnite_logement', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('indemnite_deplacement', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('indemnite_fonction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allocation_familiale', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('autres_avantages', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('salaire_brut', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cotisations_patronales', sa.JSON(), nullable=False),
    sa.Column('cotisations_salariales', sa.JSON(), nullable=False),
    sa.Column('retenues_diverses', sa.JSON(), nullable=False),
    sa.Column('total_charge_salariale', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('base_imposable', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('salaire_net', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payslip_generated', sa.Boolean(), nullable=False),
    sa.Column('payslip_file', sa.String(length=500), nullable=True),
    sa.Column('payslip_generated_at', sa.DateTime(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=False),
    sa.Column('calculated_by_id', sa.Integer(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('validated_by_id', sa.Integer(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('modification_history', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calculated_by_id'], ['user_management_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employe_id'], ['rh_employe.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['periode_paie_id'], ['paie_periode.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validated_by_id'], ['user_management_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employe_id', 'periode_paie_id', name='uq_employe_periode')
    )
    op.create_index(op.f('ix_paie_entree_id'), 'paie_entree', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paie_entree_id'), table_name='paie_entree')
    op.drop_table('paie_entree')
    op.drop_index(op.f('ix_paie_alert_id'), table_name='paie_alert')
    op.drop_table('paie_alert')
    op.drop_index(op.f('ix_paie_retenu_salaire_id'), table_name='paie_retenu_salaire')
    op.drop_table('paie_retenu_salaire')
    op.drop_index(op.f('ix_paie_periode_id'), table_name='paie_periode')
    op.drop_table('paie_periode')
    # ### end Alembic commands ###
